[components.cpio]

# Overlays live as one-logical-change-per-file under ./overlays/.
# See https://github.com/microsoft/azure-linux-dev-tools/blob/main/docs/user/reference/config/overlays.md#per-file-overlay-format-overlaytoml
overlay-dir = "overlays"
