[greeter]
theme-name = Bluecurve
icon-theme-name = Bluecurve
background = /usr/share/backgrounds/bluecurve/lightrays.png
font-name = Luxi Sans 10
xft-antialias = true
xft-hintstyle = hintmedium
show-clock = true
clock-format = %a, %b %-d  %-I:%M %p
position = 50%,center 50%,center