[LightDM]
logind-check-graphical=true

[Seat:*]
# XFCE session for all seats
user-session=xfce
# Use GTK greeter (styled with Bluecurve)
greeter-session=lightdm-gtk-greeter
autologin-guest=false
# Enable accessibility
xserver-allow-tcp=false